site_name: My Documentations
site_url: https://pat26-dotcom.github.io/website/
repo_url: https://github.com/pat26-dotcom/website
theme:
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      # ccent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: material
  
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Linux:
    - Swarm Configuration: linux/swarm.md
    - Ubuntu: linux/ubuntu.md/
  - Docker Stacks:
    - Grafana: docker/grafana.md
    - Homepage: docker/homepage.md
    - InfluxDB: docker/influxdb.md
    - Jellyfin: docker/jellyfin.md
    - Monitoring & Logging: docker/monitoring_logging.md
    - Node-Red: docker/node-red.md
    - Paperless NGX: docker/paperless.md
    - Portainer BE: docker/portainer.md
    - Stirling-PDF: docker/stirling-pdf.md

  - About:
    - About Me: about/about.md
    - Contact: about/contact.md
  - Tags: tags.md
  - Blog: 
    - blog/index.md